basic_config: &basic_config
  # Run settings
  log_to_screen: !!bool True # Log progress to screen.
  save_checkpoint: !!bool True # Save checkpoints
  checkpoint_save_interval: 10 # Save every # epochs - also saves "best" according to val loss
  true_time: !!bool False # Debugging setting - sets num workers to zero and activates syncs
  num_data_workers: 6 # Generally pulling 8 cpu per process, so using 6 for DL - not sure if best ratio
  enable_amp: !!bool False # Use automatic mixed precision - blows up with low variance fields right now
  compile: !!bool False # Compile model - Does not currently work
  gradient_checkpointing: !!bool False # Whether to use gradient checkpointing - Slow, but lower memory
  exp_dir: 'Demo_GNO'
  log_interval: 1 # How often to log - Don't think this is actually implemented
  pretrained: !!bool False # Whether to load a pretrained model
  # Training settings
  drop_path: 0.1
  batch_size: 32 #1
  max_epochs: 10
  scheduler_epochs: -1
  epoch_size: 50 #2000 # Artificial epoch size
  rescale_gradients: !!bool False # Activate hook that scales block gradients to norm 1
  # optimizer: 'adan' # adam, adan, whatever else i end up adding - adan did better on HP sweep
  optimizer: 'AdamW' # adam, adan, whatever else i end up adding - adan did better on HP sweep
  scheduler: 'cosine' # Only cosine implemented
  warmup_steps: 5 # Warmup when not using DAdapt
  learning_rate: 1e-3 # -1 means use DAdapt
  weight_decay: 1e-3
  # n_states: 12   # Number of state variables across the datasets - Can be larger than real number and things will just go unused
  # n_states: 200   # Workaround PyTorch bug
  n_states: 220   # Workaround PyTorch bug
  n_states_cond: 0
  state_names: ['Vx', 'Vy', 'Vz', 'Pressure'] # Should be sorted
  dt: 1 # Striding of data - Not currently implemented > 1
  leadtime_max: 1 #prediction lead time range [1, leadtime_max]
  n_steps: 4 # Length of history to include in input
  enforce_max_steps: !!bool False # If false and n_steps > dataset steps, use dataset steps. Otherwise, raise Exception.
  accum_grad: 1  # Real batch size is accum * batch_size, real steps/"epoch" is epoch_size / accum
  # Model settings
  model_type: 'vit_all2all'
  #space_type: '2D_attention' # Conditional on block type
  tie_fields: !!bool False # Whether to use 1 embedding per field per data
  embed_dim: 384 # Dimension of internal representation - 192/384/768/1024 for Ti/S/B/L
  num_heads: 6 # Number of heads for attention - 3/6/12/16 for Ti/S/B/L
  processor_blocks: 12 # Number of transformer blocks in the backbone - 12/12/12/24 for Ti/S/B/L
  tokenizer_heads:
    - head_name: "tk-3D"
      patch_size: [[8, 8, 8]] # z, x, y
    - head_name: "gno-flow3D"
      patch_size: [[1, 1, 1]]
      radius_in: 1.8
      radius_out: 1.9
      # resolution: [48, 48, 48]
      resolution: [16, 16, 16]
      n_channels: 4
  sts_model: !!bool False
  sts_train: !!bool False  #when True, we use loss function with two parts: l_coarse/base + l_total, so that the coarse ViT approximates true solutions directly
  bias_type: 'none'  # Options rel, continuous, none
  # Data settings
  train_val_test: [.8, .1, .1]
  augmentation: !!bool False # Augmentation not implemented
  use_all_fields: !!bool True # Prepopulate the field metadata dictionary from dictionary in datasets
  tie_batches: !!bool False # Force everything in batch to come from one dset
  extended_names: !!bool False # Whether to use extended names - not currently implemented
  embedding_offset: 0  # Use when adding extra finetuning fields
  # train_data_paths: [ ['/global/homes/a/aprokop/m4724/aprokop/Flowsaround3Dobjects/data/', 'flow3d', ''] ]
  # valid_data_paths: [ ['/global/homes/a/aprokop/m4724/aprokop/Flowsaround3Dobjects/data/', 'flow3d', ''] ]
  train_data_paths: [ ['/pscratch/sd/a/aprokop/Flowsaround3Dobjects_recompute/data/', 'flow3d', 'train', 'gno-flow3D'] ]
  valid_data_paths: [ ['/pscratch/sd/a/aprokop/Flowsaround3Dobjects_recompute/data/', 'flow3d', 'val', 'gno-flow3D'] ]
  append_datasets: [] # List of datasets to append to the input/output projections for finetuning
