basic_config: &basic_config
  # Run settings
  log_to_wandb: !!bool False #True # Use wandb integration
  log_to_screen: !!bool True # Log progress to screen.
  save_checkpoint: !!bool True # Save checkpoints
  checkpoint_save_interval: 10 # Save every # epochs - also saves "best" according to val loss
  debug_grad: !!bool True # Compute gradient/step_sizes/ect for debugging
  true_time: !!bool False # Debugging setting - sets num workers to zero and activates syncs
  num_data_workers: 4 # Generally pulling 8 cpu per process, so using 6 for DL - not sure if best ratio
  enable_amp: !!bool False # Use automatic mixed precision - blows up with low variance fields right now
  compile: !!bool False # Compile model - Does not currently work
  gradient_checkpointing: !!bool False # Whether to use gradient checkpointing - Slow, but lower memory
  exp_dir: './' # Output path
  log_interval: 1 # How often to log - Don't think this is actually implemented
  # Training settings
  drop_path: 0.1
  scheduler_epochs: -1
  rescale_gradients: !!bool False # Activate hook that scales block gradients to norm 1
  optimizer: 'adam' #'adan' # adam, adan, whatever else i end up adding - adan did better on HP sweep
  scheduler: 'cosine' # Only cosine implemented
  warmup_steps: 1000 # Warmup when not using DAdapt
  learning_rate: 1e-4 # -1 means use DAdapt
  weight_decay: 1e-3
  n_states: 15 #12   # Number of state variables across the datasets - Can be larger than real number and things will just go unused
  state_names: ['Pressure', 'Vx', 'Vy', 'Density',  'Vx', 'Vy', 'Density', 'Pressure'] # Should be sorted
  dt: 1 # Striding of data - Not currently implemented > 1
  leadtime_max: 1 #prediction lead time range [1, leadtime_max]
  n_steps: 10 # Length of history to include in input
  enforce_max_steps: !!bool False # If false and n_steps > dataset steps, use dataset steps. Otherwise, raise Exception.
  # Model settings
  model_type: "avit" #
  time_type: 'attention' # Conditional on block type
  space_type: 'axial_attention' # Conditional on block type
  tie_fields: !!bool False # Whether to use 1 embedding per field per data
  embed_dim: 192 # Dimension of internal representation - 192/384/768/1024 for Ti/S/B/L
  num_heads: 3 # Number of heads for attention - 3/6/12/16 for Ti/S/B/L
  processor_blocks: 12 # Number of transformer blocks in the backbone - 12/12/12/24 for Ti/S/B/L
  patch_size: [[32, 32]] #, [32, 32], [64, 64]] #
  bias_type: 'PositionAreaBias'  # Options rel, continuous, none
  # Data settings
  augmentation: !!bool False # Augmentation not implemented
  use_all_fields: !!bool True # Prepopulate the field metadata dictionary from dictionary in datasets
  tie_batches: !!bool False # Force everything in batch to come from one dset
  extended_names: !!bool False # Whether to use extended names - not currently implemented
  embedding_offset: 0  # Use when adding extra finetuning fields


finetune: &finetune
  <<: *basic_config
  leadtime_max_finetuning: 100 
  max_epochs: 500
  batch_size: 256 #1472  #32 #1
  epoch_size: 400 #2000 # Artificial epoch size
  #train_val_test: [.8, .1, .1]
  accum_grad: 1
  pretrained: !!bool True
  group: 'debugging'
  #pretrained_ckpt_path: 'INIT' # 
  pretrained_ckpt_path: 'pretrainedtar'
  train_data_paths: [
             ['finetuningtraindata_dir', 'liquidMetalMHD', ''],
              ]
  valid_data_paths: [  # These are the same for all configs - uses split according to train_val_test
              ['/lustre/orion/lrn037/proj-shared/liquidMetalMHD/test', 'liquidMetalMHD', ''],
              ]
  embedding_offset: 0 # Number of fields in original model - FT fields start after this
  freeze_middle: !!bool True # Whether to freeze the middle layers of the model
  freeze_processor: !!bool False
  append_datasets: ['liquidMetalMHD'] # List of datasets to append to the input/output projections for finetuning
  

